[build]
  command = "npm run build"
  publish = ".next"

# Next.js -adapteri. Netlify päivittää version automaattisesti jokaisessa buildissa,
# joten versiota ei pinnata.
[[plugins]]
  package = "@netlify/plugin-nextjs"
